### ISSUE TITLE
Bug: calcite-pick-list and calcite-value-list dark theme text isn't visible

### ISSUE THREAD

**Issue by bcree11** [Esri/calcite-components#1270]
### Summary

When dark theme is used for calcite-pick-list and calcite-value-list label text is not visible, description is barely visible, and action icons are also barely visible.

### Actual Behavior

![image](https://user-images.githubusercontent.com/45497237/99002866-02a53880-24f2-11eb-9488-b807781f3170.png)

### Expected Behavior

To be able to clearly see the text and actions on each item. I noticed that `mix-blend-mode: multiply` on label and calcite-action is causing this issue. Removing it makes the text and icon viewable.

![image](https://user-images.githubusercontent.com/45497237/99004218-962b3900-24f3-11eb-92d5-3978f66f60e2.png)

![image](https://user-images.githubusercontent.com/45497237/99004049-84e22c80-24f3-11eb-86f2-e2d11e00d1e3.png)

After removing mix-blend-mode:

![image](https://user-images.githubusercontent.com/45497237/99004283-a8a57280-24f3-11eb-94f8-672fc543b055.png)

### Reproduction Steps

https://esri.github.io/calcite-components/?path=/story/app-components-pick-list--basic&knob-dir=ltr&knob-disabled=&knob-filterEnabled=&knob-loading=&knob-multiple=&knob-theme=dark

**Comment by caripizza** [comment]
Hi @bcree11, I reproduced this issue in the components' stories, per your link example. However, I can't repro this issue in the component demos/html - the labels appear visible as do the icons. I'm wondering if this is just a Storybook-related issue due to the components sitting in an iframe. Can you please clarify for me if you have reproducible steps in a non-Storybook environment?

**Comment by caripizza** [comment]
Closing for now, if we have some repro steps in a non-Storybook environment we can re-open this one.

**Comment by Csmith246** [comment]
@caripizza Here's an example of the issue in a non-storybook environment: https://codepen.io/csmith55/pen/oNzKoKd?editors=1000. I'm loading the calcite resources from the unpkg CDN here

**Comment by caripizza** [comment]
@Csmith246 isn't it still sitting in an iframe?

**Comment by Csmith246** [comment]
@caripizza That is true for CodePen. I just copy/pasted that code to my machine and ran it locally. I'm getting the same thing. Here's a screenshot:

![image](https://user-images.githubusercontent.com/22039422/105902590-b4bdae00-5fd3-11eb-883a-a2516d7eea68.png)

In this context, it's definitely outside of an Iframe

**Comment by caripizza** [comment]
Aha - thanks for that @Csmith246. Confirmed the bug on my end too in the current v1.0.0-beta.48 release. Looks like specifically it was in the calcite-pick-list-item component, and it was fixed in this commit a couple weeks ago (ie., Alan removed the `mix-blend-mode: multiply` styles), so I'm thinking the next release should include the fix:
https://github.com/Esri/calcite-components/commit/1e3f17c61c382c8a338ed298149e7a5caddffa59#diff-09662305e87ed34c93da0a2d36016063cdde0eba67926b49a3b43799e72585f4L47:~:mix-blend-mode:%20multiply;

**Comment by Csmith246** [comment]
@caripizza We're still experiencing this issue in our codebase. Could we open this issue until the fix is published and confirmed?

**Comment by caripizza** [comment]
@Csmith246 @bcree11 based on what I'm seeing this should now be resolved in the latest release of @Esri/calcite-components@1.0.0-beta.50, can you please check on your end when you have a moment?

**Comment by Csmith246** [comment]
Looks like it's fixed in the latest version. Thanks!
