### ISSUE TITLE
Object.defineProperty throwing error to console from Calcite-components/dist runtime.js

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-components#13189]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Which Component

N/A

### Actual Behavior

We are seeing console errors thrown by code that appears to be trying to assign a property to record Calcite's version in the startup process:

<img width="869" height="422" alt="Image" src="https://github.com/user-attachments/assets/82db9608-3530-444f-9a17-92871e1c1329" />

<img width="968" height="179" alt="Image" src="https://github.com/user-attachments/assets/3b3671a0-afc1-433d-a3e3-e4a434fc73f2" />

### Expected Behavior

This isn't impacting any behavior, but we'd prefer not to have console errors in the application from libraries.

### Reproduction Sample

Knowledge Studio

### Reproduction Steps

I am not totally sure what causes this, but I have some ideas.  When I set breakpoints between Studio and StackBlitz on this line, I noticed that studio gets the version "target" variable from the globalThis["calciteConfig" access whereas your StackBlitz test environment just has target as an anonymous object since calciteConfig isn't in globalThis.

I think that you just have a simple error here where you need to add a condition so that Object.defineProperty isn't used if the version is already present on globalThis in the calcite config, like so:

if (!target.version) {
  Object.defineProperty(target, "version", {
    value: version,
    writable: false
  });
  globalThis["calciteConfig"] = target;
}

Conceptually, it seems to make sense to me that you don't need to assign the version if you already have it.

It seems like this is occurring whenever a client runs this initialization script twice (perhaps this happens between the SDK and calcite-components libraries both being present?), then the second time it runs it fails because the calciteConfig has already been set.  this theory is supported by the fact that I see the console.log outputted twice in my client and it fails after the second time

<img width="794" height="128" alt="Image" src="https://github.com/user-attachments/assets/bcc6648a-5224-4a2c-8df0-e7ae8306a95e" />

### Reproduction Version

3.3.0

### Relevant Info

Like I say above, I believe the error occurs when the script that outputs the Calcite version runs more than once on application load.

### Priority impact

impact - p3 - not time sensitive

### Impact

Low impact - it's just bad to have errors getting thrown from libraries and we try to eliminate it

### Calcite package

- [ ] @esri/calcite-components
- [x] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Knowledge

**Comment by jcfranco** [comment]
@RSantosGIS This might already be resolved by https://github.com/Esri/calcite-design-system/pull/13258. Can you retest once you’ve migrated to the next major release (v5)?

**Comment by RSantosGIS** [comment]
Sure thing, I'll add it to our tracking ticket for the upgrade

**Comment by Alkari07** [comment]
@jcfranco this problem is still occurring.  It most recently manifested when we added arcgis-charts to our project, which still apparently has some internal dependency on Calcite 3.3.3 floating around.  Here you can see where the version property is already defined as 5.0 (the version of the JS SDK and calcite in use by Studio), but arcgis-charts is trying to set it to 3.3.3:

<img width="576" height="249" alt="Image" src="https://github.com/user-attachments/assets/281decee-cf69-4109-8993-e9e426d16f77" />

<img width="594" height="229" alt="Image" src="https://github.com/user-attachments/assets/cffe1375-d7e8-4d18-8f08-0c26f910f47b" />

<img width="810" height="253" alt="Image" src="https://github.com/user-attachments/assets/e5a449cd-dc0f-43c7-b718-77012f8f6875" />

I'm not sure if this is something that we just need charts to fix, but the error is being thrown from Calcite's runtime file and I still think a conditional "if statement" wrapper where you do not do this assignment if it is unsafe and would crash the app is warranted.  Also, this is blocking our development of arcgis-charts integration.

CC @macandcheese

**Comment by Alkari07** [comment]
@geospatialem if possible, we need the priority of this bumped up from p3 to p1, since it is now blocking our feature development.  Like I said above, it is possible that another way to unblock us would be just to have arcgis-charts update whatever 3.3.3 calcite dependency they still have lurking around.  Perhaps if they do that, the fix @jcfranco already mentioned will make this not happen?  Not sure.  Regardless, I do think that it should never be possible that Calcite makes an unsafe assignment like this where it could crash an app based on something as mundane as version logging.

**Comment by Alkari07** [comment]
Relevant versions:
SDK: 5.0.0-next.63
calcite: 5.0.0-next.25
charts: 5.0.0-next.28

**Comment by Alkari07** [comment]
@geospatialem @jcfranco On further investigation, this is not blocking.  There is an uncaught error being thrown to console but the problem that was preventing the app from loading was something else.  So while this kind of thing still makes me nervous since code after the error in Calcite libraries is not executing, it does not seem to be breaking  / blocking as far as I can tell atm.
