### ISSUE TITLE
React CalciteDropdownItem `active` property isn't passed through correctly

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-components#4543]
### Actual Behavior

1. Setting the `active` property of CalciteDropdownItem to a boolean variable (like `isActive`) results in all items displaying as active even if they are false.
2. Setting the `active` property to a boolean variable or null (like `isActive || null`), results in a console error `TypeError: can't access property "toString", this.active is null`

### Expected Behavior

I would expect both `isActive` and `isActive || null` to correctly set the active state of the dropdown based on the variable value.

### Reproduction Sample

https://codesandbox.io/s/priceless-heisenberg-1vjxvm?file=/src/App.js

### Reproduction Steps

1. Open the code sandbox
2. Click to open the first dropdown and you will see all items marked as active
3. Click to open the second dropdown and you will only see one item even though there should be three. Also, there is an error in the console.

### Reproduction Version

beta.82

**Comment by jcfranco** [comment]
Closing as this was fixed by https://github.com/Esri/calcite-components/issues/4462. See https://codesandbox.io/s/zealous-river-wcf0ch?file=/src/App.js.

**Comment by noahmulfinger** [comment]
@jcfranco Looks like item 1 above still isn't addressed because all the dropdown items still show up as active in the first dropdown in your sandbox

**Comment by benelan** [comment]
`calcite-components-react` includes  `calcite-components` as a dependency. Not sure how it handles adding a different CC version as a dep like in Franco's example (especially while in prerelease). We should wait and retest next week after the release so CCR will have the fixed CC version as a dep.

**Comment by jcfranco** [comment]
There's been a misunderstanding, let me clarify:

1. We still need the gotcha section for the way that React handles boolean attributes. This hasn't changed.
2. The fix I mentioned above was specific to the observed error in the repro case (caused by components using the value of boolean props to set ARIA attributes).
3. > Looks like item 1 above still isn't addressed because all the dropdown items still show up as active in the first dropdown in your sandbox
  
    Item 1 works according to the gotcha where anything other than `null` or `undefined` gets set as a truthy value.

**Comment by benelan** [comment]
Oh okay, thanks for the clarification. This is the [gotcha documentation](https://developers.arcgis.com/calcite-design-system/frameworks/#gotchas) Franco is referring to.

**Comment by benelan** [comment]
We already have issue open for the problem described in the gotcha section, which you can track until stencil addresses it #3230

**Comment by noahmulfinger** [comment]
@jcfranco @benelan Got it, thanks for the clarification. In some cases the null/undefined gotcha doesn't seem to happen for the React wrappers, so I assumed it was fixed generally.
