### ISSUE TITLE
Keyboard input does not work in Filter by date if your user locale is set to Arabic

### ISSUE THREAD

**Issue by Olga8614** [Esri/calcite-components#4569]
### Actual Behavior

devext, 05/17/2022
Steps:
1. Set your user locale to Arabic (key step)
2. Go to My Contents tab, or any other tab that has Custom range filter by date
3. Click the Start Date or End Date and observe:  calendar displays with Indic Numerals
![image](https://user-images.githubusercontent.com/29614798/168915058-a55f3b13-4ef7-499c-aa26-93c8d7afa237.png)
4. Try to edit the year by manually entering 2021 or 2020 with your keyboard
Observe: the change does not take effect

Entering 20:
![image](https://user-images.githubusercontent.com/29614798/168915439-e70c88bd-c108-42a2-b682-862e13eca8d9.png)

2020 becomes 2022 again after you click Enter:
![image](https://user-images.githubusercontent.com/29614798/168915524-b2bb65d7-7608-4def-a992-27b045cf1156.png)

5. Try to edit the Start date or End date manually by entering with your keyboard input

![image](https://user-images.githubusercontent.com/29614798/168915821-95630ed6-beac-46aa-8ef7-92489ac562c0.png)

Observe: custom filter by date does not take effect.

![image](https://user-images.githubusercontent.com/29614798/168916219-27a4105d-d57d-4109-a5de-3916aec1d9e4.png)

6. Set Start Date and End date with your mouse using UI controls and notice that filter is set.
![image](https://user-images.githubusercontent.com/29614798/168916494-5f8d42df-36dc-444c-9c99-15aa179c4d8a.png)

7. Edit Start or End date set on Step 6 with your keyboard and notice that changes don't take effect.

![image](https://user-images.githubusercontent.com/29614798/168916837-c8229b44-a790-48ca-beaf-89a3caf9ce21.png)

### Expected Behavior

Keyboard input should work and take effect on filter
cc @aine

### Reproduction Sample

.

### Reproduction Steps

Steps:
1. Set your user locale to Arabic (key step)
2. Go to My Contents tab, or any other tab that has Custom range filter by date
3. Click the Start Date or End Date and observe:  calendar displays with Indic Numerals
![image](https://user-images.githubusercontent.com/29614798/168915058-a55f3b13-4ef7-499c-aa26-93c8d7afa237.png)
4. Try to edit the year by manually entering 2021 or 2020 with your keyboard
Observe: the change does not take effect

Entering 20:
![image](https://user-images.githubusercontent.com/29614798/168915439-e70c88bd-c108-42a2-b682-862e13eca8d9.png)

2020 becomes 2022 again after you click Enter:
![image](https://user-images.githubusercontent.com/29614798/168915524-b2bb65d7-7608-4def-a992-27b045cf1156.png)

5. Try to edit the Start date or End date manually by entering with your keyboard input

![image](https://user-images.githubusercontent.com/29614798/168915821-95630ed6-beac-46aa-8ef7-92489ac562c0.png)

Observe: custom filter by date does not take effect.

![image](https://user-images.githubusercontent.com/29614798/168916219-27a4105d-d57d-4109-a5de-3916aec1d9e4.png)

6. Set Start Date and End date with your mouse using UI controls and notice that filter is set.
![image](https://user-images.githubusercontent.com/29614798/168916494-5f8d42df-36dc-444c-9c99-15aa179c4d8a.png)

7. Edit Start or End date set on Step 6 with your keyboard and notice that changes don't take effect.

![image](https://user-images.githubusercontent.com/29614798/168916837-c8229b44-a790-48ca-beaf-89a3caf9ce21.png)

### Reproduction Version

devext.arcgis.com as of 05/07/2022

**Comment by annierm18** [comment]
https://jsbin.com/gasununuwi/1/edit?html,output

**Comment by jcfranco** [comment]
@Olga8614 @annierm18 I have a few questions since there's a few moving parts in the description:

1. Based on the codepen above, does https://github.com/Esri/calcite-components/issues/2095 represent the main issue? If so, we can close this as a duplicate.
2. If the answer to☝️ is no, can you provide more info on what is not working on the component side that is affecting date filtering?

**Comment by Olga8614** [comment]
@jcfranco - the answer to 1. is no. 
Currently the input with Western numerals is not working.
Expected behavior: no matter if you input Western or Indic digits, the inputbox should take it and interpret as numbers.

**Comment by Olga8614** [comment]
> @jcfranco @Olga8614 I am wondering why Beyondsoft has not found this critical issue, when testing the client apps (those that are using this Calcite control)?! I would like to pursue that side of things :)

@babakboluor because the issue I reported was discovered on hyperdev. BYS needs esri VPN to test on hyperdev.

**Comment by jcfranco** [comment]
This is still valid after latest updates to the component: https://codepen.io/jcfranco/pen/wvEJPEY

**Comment by eriklharper** [comment]
I _think_ this is fixed now on the latest `1.4.1`.  @Olga8614 would you be able to re-verify this with the latest calcite version?  I forked Franco's codepen with the latest calcite and my keyboard edits are working after changing the value and pressing enter or blurring the input.

**Comment by Olga8614** [comment]
> I _think_ this is fixed now on the latest `1.4.1`. @Olga8614 would you be able to re-verify this with the latest calcite version? I forked Franco's codepen with the latest calcite and my keyboard edits are working after changing the value and pressing enter or blurring the input:
> 
> https://codepen.io/eriklharper/pen/wvYVvzE

The year can be edited from the keyboard - fixed
The day input from the keyboard still does not take effect - not fixed

![image](https://github.com/Esri/calcite-components/assets/29614798/697bc052-1960-4844-a629-89c4a416852d)

**Comment by eriklharper** [comment]
I've created this issue, which explains the larger bug at play here: the inability to intuitively edit the date value text in the input when in RTL mode: https://github.com/Esri/calcite-components/issues/7186
